# Root logging level (global)
logging.level.root=INFO

# Specific package or class logging level
logging.level.com.example.myapp=DEBUG
logging.level.org.springframework=WARN

# Log file location (optional)
logging.file.name=C:/RajKadam/property-rental/logs/property-rental-service.log

spring.application.name=property-rental-service
spring.data.mongodb.uri=mongodb://localhost:27017/property-rental

# JWT Configuration
jwt.secret=YourSuperSecretKeyThatIsAtLeast256BitsLongForHS256AlgorithmSecureKey2024
jwt.expiration=86400000

resilience4j:
    ratelimiter:
        instances:
            login:
                limitForPeriod: 5
                limitRefreshPeriod: 15m
                timeoutDuration: 0s
                registerHealthIndicator: true
                eventConsumerBufferSize: 100